server:
  port: 8080
  servlet:
    context-path: /Mybatis-plus

logging:
  level:
    root: info
    # 将mapper(dao)接口所在包的日志级别改成debug,可以在控制台打印sql
    com:
      xihua:
        dao: debug
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://192.168.227.135:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化数量
      initiaSize: 5
      minIdle: 5
      # 最大活跃数
      maxActive: 20
      # 最大连接等待超时时间
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECE 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache,并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      #配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat,wall,log4j
      filter:
        slf4j:
          enabled: true
      maxPoolPrepareStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectionProperties属性打开mergeSql功能；慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#分页导航
navigatePages: 5

#pagehelper分页插件配置 以下属性不加也可以实现分页功能
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: 0
  count: countSql

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xihua.entity
  type-handlers-package: com.xihua.handler
  type-enums-package: com.xihua.handler
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名）
    #到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: true
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
